languageCode = "en"
languageName = "ＥＮＧ"
weight = 3
title = "ダヒのBlog"

[params]
  displayName = "ＥＮＧ"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  description = "Blog"

[author]
  name = "Dahi"
  image = "https://oxs.dahi.icu/pic/avatar.png"
  headline = "Here"
  bio = "A student"
  links = [
    { github = "https://github.com/dahisea" }
  ]
