languageCode = "en"
languageName = "ＥＮＧ"
weight = 3
title = "ダヒのBlog"

[params]
  displayName = "ＥＮＧ"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  description = "Blog"

[author]
  name = "Dahi"
  image = "https://img3.tapimg.com/avatars/etag/FrXPfpRN0pwF5SuiQ7MIPO3BXdkK.png?imageMogr2/auto-orient/strip/format/webp"
  headline = "Here"
  bio = "A student"
  links = [
    { github = "https://github.com/dahisea" }
  ]
