languageCode = "zh-TW"
languageName = "繁體字"
weight = 3
title = "大海Dahi的部落格世界"

[params]
  displayName = "繁體字"
  isoCode = "zh-TW"
  rtl = false
  dateFormat = "2006-01-02"
  description = "Welcome to Dahi的部落格"

[author]
  name = "Dahi"
  image = "https://img3.tapimg.com/avatars/etag/FrXPfpRN0pwF5SuiQ7MIPO3BXdkK.png"
  headline = "ようこそ"
  bio = "Studying"
  links = [
    { github = "https://github.com/dahisea" }
  ]
