languageCode = "ja"
languageName = "日本語"
weight = 3
title = "大海DahiのBlog世界"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006-01-02"
  description = "Welcome to Dahi Blog"

[author]
  name = "Dahi"
  image = "https://img3.tapimg.com/avatars/etag/FrXPfpRN0pwF5SuiQ7MIPO3BXdkK.png"
  headline = "ようこそ"
  bio = "Studying"
  links = [
    { github = "https://github.com/dahisea" }
  ]
