# -- メインメニュー --
# メインメニューはページトップのヘッダーに表示されます。
# 利用可能なパラメーターは name, pageRef, page, url, title, weight です。
# 
# 最もシンプルなメニュー設定はこちらです:
#   name = このメニューリンクに表示される名前
#   pageRef = ページやセクションのリンクに利用される識別子
#
# デフォルトでは、メニューはアルファベット順に並べられます。
# これは、 weight value で上書き可能です。
# このメニューは weight が低い値から高い値に順に表示されます。

[[main]]
  name = "Article"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Article"
  pageRef = "posts"
  weight = 40

 [[main]]
   name = "TOMODACHI"
   pageRef = "TOMODACHI"
   weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/dahisea"
  weight = 400


# -- フッターメニュー --
# このフッターメニューはページ下部のコピーライト表示の前に表示されます。
# 上記のメインメニューと同様に設定できます。

 [[footer]]
   name = "TAG"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "DNS"
   pageRef = "DNS"
   weight = 20

 [[footer]]
   name = "TOMODACHI"
   pageRef = "TOMODACHI"
   weight = 20
   
 [[footer]]
   name = "DONATE"
   pageRef = "DONATE"
   weight = 20