baseURL = "https://dahi.icu/"
languageCode = "zh-TW"
defaultContentLanguage = "zh"
title = "Dahi Blog"
theme = "kagome"
paginate = 5
copyright = "轉載註明來源　© Long term Dahi.icu"
hasCJKLanguage = true
  
# 作者信息
[author]
  name = "Dahi"
  email = "expect@dahi.icu"
  description = "願你有一天能與你重要的人重逢"
  avatar = "https://s1.ax1x.com/2023/08/01/pP9zpXd.png"
  
[menu]
  [[menu.main]]
    identifier = "tomodachi"
    name = "友人"
    url = "/tomodachi/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "dns"
    name = "DNS"
    url = "/dns/"
    weight = 3
  [[menu.main]]
    identifier = "link"
    name = "Don't attack"
    url = "/link/"
    weight = 4

  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/dahisea"
    weight = 1
    [[menu.social]]
    identifier = "telegram"
    name = "telegram"
    url = "https://t.me/Unit_O"
    weight = 2
    



[params]
  keywords = ['Dahi']
  description = "時光流轉，願你有一天能與重要的人重逢"
  mainSections = ["posts"]
  
  [params.widget]
    articles_count = 9
    categories_count = 3
    tags_count = 6

