[build]
  command = "hugo --gc --minify -D -b $URL"
  publish = "public"

[build.environment]
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"
TZ = "Portugal/Lisbon"

[context.production.environment]
HUGO_VERSION = "0.104.1"
HUGO_ENV = "production"
